version: '3.3'  
services:  
  web:
    image: webtest
    #ports:
    #- '5001:5000'
  nginx:
    image: nginx:1.11
    links:
    - 'web'
    ports:
    - '5000:80'
    command: |
      /bin/bash -c "echo '
      server {
        listen 80;
        location / {
            proxy_pass http://web:5000;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"